using Lambda;

// Basic bot generated by Claude Code

/**
	Model classes
*/
typedef Vec = { x : Int, y : Int };
typedef Robot = { pos : Vec };
typedef Object = { pos : Vec };
typedef Inventory = { scrap : Int, microship : Int };
typedef GameState = {
	inv : Inventory,
	me : { robots : Array<Robot>},
	foes : { robots : Array<Robot> },
	mines : Array<Object>,
	scraps : Array<Object>,
	microships : Array<Object>,
};

class MinesClaudeBot {

	static final stdin = Sys.stdin();
	static final stdout = Sys.stdout();

	static var PID : Int;
	static var WIDTH : Int;
	static var HEIGHT : Int;

	// Mirrors server.Simulation costs (bots don't share code with the server).
	static final ROBOT_COST_SCRAP = 5;
	static final ROBOT_COST_MICROSHIP = 1;
	static final MINE_COST_SCRAP = 4;

	static final MAX_ROBOTS = 10; // keep growth from getting silly, not a hard game rule
	static final MINE_RESERVE = ROBOT_COST_SCRAP; // always keep enough scrap for the next spawn

	static final REG_INT = ~/^(\d+)$/;
	static function readInt() : Int {
		final line = stdin.readLine();
		if (!REG_INT.match(line)) throw 'Int expected, received "$line"';
		return Std.parseInt(REG_INT.matched(1));
	}

	static final REG_VEC = ~/^(\d+) (\d+)$/;
	static function readVec() : Vec {
		final line = stdin.readLine();
		if (!REG_VEC.match(line)) throw 'Vec expected, received "$line"';
		return {
			x : Std.parseInt(REG_VEC.matched(1)),
			y : Std.parseInt(REG_VEC.matched(2)),
		};
	}

	static function parseState() : GameState {
		static final REG_HEADER = ~/^([A-Z]+) (\d+)$/;

		function readSection<T : {}>(name : String, f : { pos : Vec } -> T) : Array<T> {
			final line = stdin.readLine();
			if (!REG_HEADER.match(line) || REG_HEADER.matched(1) != name) throw 'Header "$name" expected, received "$line"';

			var res = [];
			final c = Std.parseInt(REG_HEADER.matched(2));
			for (_ in 0...c) {
				res.push(f({ pos : readVec() }));
			}
			return res;
		}

		var state : GameState = {
			inv : {
				scrap : readInt(),
				microship : readInt(),
			},
			me : { robots : readSection("ME", o -> (o : Robot)) },
			foes : { robots : readSection("FOES", o -> (o : Robot)) },
			mines : readSection("MINE", o -> (o : Object)),
			scraps : readSection("SCRAP", o -> (o : Object)),
			microships : readSection("MICROSHIP", o -> (o : Object)),
		}
		return state;
	}

	public static inline function debug(msg : String) Sys.stderr().writeString('$msg\n');

	public static inline function getName() return "Claude";

	public static function main() {
		final args = Sys.args();
		if (args.indexOf("--config") != -1) {
			stdout.writeString('${getName()}\n');
			return;
		}

		PID = readInt();
		var dim = readVec();
		WIDTH = dim.x;
		HEIGHT = dim.y;

		debug('Player $PID');

		while (true) loop();
	}

	static inline function dist(a : Vec, b : Vec) : Int {
		return Math.round(Math.abs(a.x - b.x) + Math.abs(a.y - b.y));
	}

	/**
		Mirrors Simulation.getClosestCellAround (same neighbor order, no shuffling) used by
		the server to resolve a Move (and, once already adjacent, a Mine) action: among the
		4 grid neighbors of [from], pick whichever is closest to [to]. Passing a real
		[exclude] predicate lets us know in advance which cell WE would actually land on and
		avoid ever stepping onto a known mine; passing "never exclude" instead lets us predict
		where an opponent who doesn't bother with that check will end up.
	*/
	static function bestNeighbor(from : Vec, to : Vec, exclude : Vec -> Bool) : Vec {
		var candidates = [];
		if (from.x - 1 >= 0) candidates.push({x : from.x - 1, y : from.y});
		if (from.x + 1 < WIDTH) candidates.push({x : from.x + 1, y : from.y});
		if (from.y - 1 >= 0) candidates.push({x : from.x, y : from.y - 1});
		if (from.y + 1 < HEIGHT) candidates.push({x : from.x, y : from.y + 1});

		var best : Vec = null;
		var bestD = 0x7fffffff;
		for (c in candidates) {
			if (exclude(c)) continue;
			var d = dist(c, to);
			if (d < bestD) {
				bestD = d;
				best = c;
			}
		}
		return best;
	}

	static function cellKey(c : Vec) return '${c.x},${c.y}';

	static function loop() {
		final state = parseState();

		function isMine(p : Vec) return state.mines.exists(m -> m.pos.x == p.x && m.pos.y == p.y);
		function noExclusion(p : Vec) return false;

		// --- Enemy tracking --------------------------------------------------
		// Ties on the exact same cell are resolved by player iteration order on the
		// server, and player 0 always goes first - so player 0 can afford to contest
		// a dead-even race, while player 1 needs to be strictly faster to actually win it.
		function canWinRace(myDist : Int, enemyDist : Int) return PID == 0 ? myDist <= enemyDist : myDist < enemyDist;

		function closestEnemyDistTo(p : Vec) : Int {
			var best = 0x7fffffff;
			for (f in state.foes.robots) {
				var d = dist(p, f.pos);
				if (d < best) best = d;
			}
			return best;
		}

		final rawResources = state.scraps.map(o -> o.pos).concat(state.microships.map(o -> o.pos));

		// Predicts where a foe robot will be after this turn's move resolves, assuming it
		// (like most simple bots) just heads for its nearest visible resource and ignores
		// mines. A mine dropped exactly on that predicted cell detonates the instant they
		// step on it - in the very same turn, since move/mine/collision all resolve in order.
		function predictNext(e : Vec) : Vec {
			var target : Vec = null;
			var bestD = 0x7fffffff;
			for (r in rawResources) {
				var d = dist(e, r);
				if (d < bestD) {
					bestD = d;
					target = r;
				}
			}
			if (target == null) return e;
			var step = bestNeighbor(e, target, noExclusion);
			return step != null ? step : e;
		}

		var ambushCells = state.foes.robots.map(f -> predictNext(f.pos));

		// A few cells around each foe, away from its predicted path, so multiple hunters
		// spread out and box it in instead of all piling onto the same tile.
		var flankPool = [];
		for (f in state.foes.robots) {
			for (off in [{x : -2, y : 0}, {x : 2, y : 0}, {x : 0, y : -2}, {x : 0, y : 2}]) {
				var c = {x : f.pos.x + off.x, y : f.pos.y + off.y};
				if (c.x >= 0 && c.x < WIDTH && c.y >= 0 && c.y < HEIGHT && !isMine(c))
					flankPool.push(c);
			}
		}

		// --- Resource targets, weighted and denial-aware ----------------------
		// Microships are worth chasing over slightly closer scrap. Resources the enemy can
		// clearly reach first aren't worth wasting a turn on; ones we can still win (or that
		// are just barely contested) get a priority bump, since denying the enemy's economy
		// is worth as much as growing our own.
		var targets = state.scraps.map(o -> {pos : o.pos, weight : 1.0})
			.concat(state.microships.map(o -> {pos : o.pos, weight : 0.6}));

		function bestResourceFor(p : Vec) {
			var best = null;
			var bestScore = 1e18;
			for (t in targets) {
				var myDist = dist(p, t.pos);
				var enemyDist = closestEnemyDistTo(t.pos);
				var score = myDist * t.weight;
				if (enemyDist < 0x7fffffff)
					score *= canWinRace(myDist, enemyDist) ? 0.5 : 1000;
				if (score < bestScore) {
					bestScore = score;
					best = t;
				}
			}
			return best;
		}

		var scrapLeft = state.inv.scrap;
		var microshipLeft = state.inv.microship;
		var spawned = false;
		var minedCells = new Map<String, Bool>();

		for (bot in state.me.robots) {
			// 1. grow the army - one new robot per turn as soon as we can afford it
			if (!spawned && state.me.robots.length < MAX_ROBOTS
				&& scrapLeft >= ROBOT_COST_SCRAP && microshipLeft >= ROBOT_COST_MICROSHIP) {
				stdout.writeString('SPAWN\n');
				spawned = true;
				scrapLeft -= ROBOT_COST_SCRAP;
				microshipLeft -= ROBOT_COST_MICROSHIP;
				continue;
			}

			// 2. kill shot - if we're exactly adjacent to a cell a foe is about to step
			// into, drop a mine there now instead of chasing it around the map.
			if (scrapLeft >= MINE_COST_SCRAP + MINE_RESERVE) {
				var killCell : Vec = null;
				for (c in ambushCells) {
					if (dist(bot.pos, c) == 1 && !minedCells.exists(cellKey(c))) {
						killCell = c;
						break;
					}
				}
				if (killCell != null) {
					stdout.writeString('MINE ${killCell.x} ${killCell.y}\n');
					minedCells.set(cellKey(killCell), true);
					scrapLeft -= MINE_COST_SCRAP;
					continue;
				}
			}

			// 3. otherwise collect (or contest) the most valuable reachable resource
			var t = bestResourceFor(bot.pos);
			if (t != null) {
				targets.remove(t);

				if (dist(bot.pos, t.pos) == 0) {
					// already standing on it, pickup resolves on its own
					stdout.writeString('WAIT\n');
					continue;
				}

				if (bestNeighbor(bot.pos, t.pos, isMine) != null) {
					stdout.writeString('MOVE ${t.pos.x} ${t.pos.y}\n');
					continue;
				}
				// every safe direction towards this target is blocked by a mine this turn
			}

			// 4. nothing to collect - close in on a foe, either chasing its predicted path
			// or taking a flanking cell so we surround rather than stack on one square.
			if (state.foes.robots.length > 0) {
				var chase : Vec = null;
				var chaseD = 0x7fffffff;
				for (c in ambushCells) {
					var d = dist(bot.pos, c);
					if (d < chaseD) {
						chaseD = d;
						chase = c;
					}
				}

				var flank : Vec = null;
				var flankD = 0x7fffffff;
				for (c in flankPool) {
					var d = dist(bot.pos, c);
					if (d < flankD) {
						flankD = d;
						flank = c;
					}
				}

				var goal = (chase != null && chaseD <= flankD) ? chase : flank;
				if (goal == flank && flank != null) flankPool.remove(flank);

				if (goal != null && bestNeighbor(bot.pos, goal, isMine) != null) {
					stdout.writeString('MOVE ${goal.x} ${goal.y}\n');
					continue;
				}
			}

			stdout.writeString('WAIT\n');
		}
		stdout.flush();
	}
}
